"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, BarChart3, CircleDollarSign, Download, PiggyBank, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { LoadingState } from "@/components/crm/Modal";
import type { AppUser, DashboardData } from "@/components/crm/types";
import { api } from "@/components/crm/utils";

type Currency={money:(cents:number)=>string};
export function ReportsView({user,currency,refreshKey}:{user:AppUser;currency:Currency;refreshKey:number}){const[data,setData]=useState<DashboardData|null>(null);useEffect(()=>{void api<DashboardData>("/api/dashboard").then(setData)},[refreshKey]);if(!data)return <LoadingState/>;const recovered=data.stats.activeCapitalCents+data.stats.expectedProfitCents-data.stats.portfolioCents;const realized=recovered-data.stats.activeCapitalCents;return <div className="reports-layout"><section className="report-hero"><div><p>RESULTADO DE CARTERA ACTIVA</p><h2>{currency.money(realized)}</h2><span>Resultado realizado temporal: cobrado menos capital colocado</span></div><BarChart3/></section><section className="report-card-grid"><article><span className="blue"><WalletCards/></span><div><small>Cartera pendiente</small><strong>{currency.money(data.stats.portfolioCents)}</strong><p>{data.stats.activeCredits} créditos</p></div></article><article><span className="aqua"><TrendingUp/></span><div><small>Interés proyectado</small><strong>{currency.money(data.stats.expectedProfitCents)}</strong><p>20% sobre capital</p></div></article><article><span className="violet"><CircleDollarSign/></span><div><small>Cobrado hoy</small><strong>{currency.money(data.stats.collectedTodayCents)}</strong><p>Registro en tiempo real</p></div></article><article><span className="orange"><AlertTriangle/></span><div><small>Créditos vencidos</small><strong>{data.stats.overdue}</strong><p>Requieren seguimiento</p></div></article></section><section className="profit-explainer"><header><div><PiggyBank/><span><strong>Cómo se mide cada crédito</strong><small>Cálculo transparente y sin mezclar microseguro con deuda</small></span></div></header><div className="profit-columns"><div><TrendingUp/><strong>Ganancia proyectada</strong><span>Interés pactado del 20% sobre el capital.</span></div><div><CircleDollarSign/><strong>Resultado realizado</strong><span>Total cobrado menos capital colocado.</span></div><div><TrendingDown/><strong>Pérdida final</strong><span>Saldo irrecuperable al registrar un crédito como pérdida.</span></div></div></section><section className="report-table-card"><header><div><h3>Créditos con mayor saldo</h3><p>Prioridad financiera de la cartera</p></div><button className="secondary-button" onClick={()=>window.print()}><Download/>Imprimir</button></header>{data.urgentCredits.sort((a,b)=>b.balanceCents-a.balanceCents).map((credit)=><div className="report-row" key={credit.id}><span>{credit.client.name}</span><strong>{currency.money(credit.principalCents)}</strong><strong>{currency.money(credit.balanceCents)}</strong><b className={credit.daysRemaining<0?"danger-text":""}>{credit.daysRemaining<0?`${Math.abs(credit.daysRemaining)} días vencido`:`${credit.daysRemaining} días`}</b></div>)}</section>{user.role==="COLLECTOR"&&<p className="scope-note">Este reporte contiene únicamente tu cartera asignada.</p>}</div>}
