"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, LoaderCircle } from "lucide-react";
import { authClient } from "@/lib/auth/client";

export function ChangePasswordForm() {
  const router = useRouter(); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const strong = newPassword.length >= 10 && /[A-Z]/.test(newPassword) && /[a-z]/.test(newPassword) && /\d/.test(newPassword);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!strong) return setError("La nueva contraseña no cumple los requisitos"); if (newPassword !== confirm) return setError("Las contraseñas no coinciden"); setLoading(true); const result = await authClient.changePassword({ currentPassword, newPassword, revokeOtherSessions: true }); if (result.error) { setError("La contraseña actual no es correcta"); setLoading(false); return; } const response = await fetch("/api/profile/complete-password", { method: "POST" }); if (!response.ok) { setError("No se pudo completar el cambio"); setLoading(false); return; } router.replace("/app"); router.refresh(); }
  return <form className="auth-form compact" onSubmit={submit}><div className="auth-heading"><span>Primer acceso</span><h1>Crea tu contraseña</h1><p>Por seguridad debes reemplazar la contraseña temporal.</p></div><label className="field"><span>Contraseña temporal</span><input type="password" value={currentPassword} onChange={(e)=>setCurrentPassword(e.target.value)} required autoFocus/></label><label className="field"><span>Nueva contraseña</span><input type="password" value={newPassword} onChange={(e)=>setNewPassword(e.target.value)} required/></label><label className="field"><span>Repite la nueva contraseña</span><input type="password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} required/></label><div className="password-rules"><span className={newPassword.length>=10?"ok":""}><CheckCircle2/>10 caracteres</span><span className={/[A-Z]/.test(newPassword)&&/[a-z]/.test(newPassword)?"ok":""}><CheckCircle2/>Mayúscula y minúscula</span><span className={/\d/.test(newPassword)?"ok":""}><CheckCircle2/>Un número</span></div>{error&&<div className="form-error">{error}</div>}<button className="primary-button full" disabled={loading}>{loading?<><LoaderCircle className="spin"/>Guardando…</>:"Guardar y continuar"}</button></form>;
}
